title: Meshtastic Rheinland
description: Infos, Setup und Community-Links für Meshtastic im Rheinland
url: https://your-username.github.io/meshtastic-rheinland
baseurl: ""

# GitHub Pages + Remote Theme
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark

logo: /assets/logo.svg
favicon_ico: /assets/favicon.ico

search: true
aux_links:
  Meshtastic Documentation:
    - https://meshtastic.org/docs
  Meshtastic Forum:
    - https://meshtastic.discourse.group/
  Meshtastic Discord:
    - https://discord.gg/meshtastic

callouts:
  note:
    title: Hinweis
    color: blue
  warning:
    title: Achtung
    color: red

nav_external_links:
  - title: GitHub Repo
    url: https://github.com/your-username/meshtastic-rheinland

# Site variables (easy to maintain)
whatsapp_invite_url: "# BITTE ERSETZEN: https://chat.whatsapp.com/DEIN-EINLADUNGS-LINK"
public_mqtt_note: ""

